apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ${cluster-name}-${host-name}
  creationTimestamp: null
spec:
  runStrategy: Always
  template:
    metadata:
      creationTimestamp: null
      labels:
        cluster: ${cluster-name}
    spec:
      #      nodeSelector:
      #    kubernetes.io/hostname: ryzen1
      domain:
        cpu:
          model: host-passthrough
        resources:
          limits:
            cpu: 4
            memory: 16Gi
        devices:
          disks:
          - name: containerdisk
            disk:
              bus: virtio
          - name: cloudinit
            disk:
              bus: virtio
          - name: mypvcdisk
            disk:
              # This makes it exposed as /dev/vda, being the only and thus first
              # disk attached to the VM
              bus: virtio
          interfaces:
            - sriov: {}
              name: default-net
                #            - bridge: {}
                #              name: marcel-vn
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 1.1.1.1
          - 8.8.8.8
      networks:
      - name: default-net
        multus:
          networkName: ${network}
        #  pod: {} # Uses default Volterra CNI as for vk8s pods
          #      - name: marcel-vn
          #        multus: # Secondary multus network
          #          networkName: ves-system/marcel-vn-internet
      volumes:
        - name: containerdisk
          containerDisk:
            image: ${f5xc_rhel9_container}
            #            imagePullPolicy: Always
        - name: mypvcdisk
          containerDisk:
            image: us-west1-docker.pkg.dev/solutions-team-280017/vesio-ver9-ce/mw-disk:10G
        - name: cloudinit
          cloudInitNoCloud:
            userData: |
              #cloud-config
              users:
                - name: "vesop"
                  passwd: ""
                  groups:
                    - "sudo"
              coreos:
                update:
                  reboot-strategy: "off"
              network:
                version: 2
              write_files:
              - path: /etc/udev/rules.d/50-disable-eth.rules
                permissions: 0644
                owner: root
                content: |
                  ACTION=="add", SUBSYSTEM=="net", SUBSYSTEMS=="pci", RUN+="/bin/sh -c '/sbin/ip link set enp6s0 name eth0'"
              - path: /etc/vpm/config.yaml
                permissions: 0644
                owner: root
                content: |
                  Kubernetes:
                    EtcdUseTLS: true
                    Server: vip
                  Vpm:
                    ClusterName: ${cluster-name}
                    ClusterType: ce
                    Config: /etc/vpm/config.yaml
                    Labels:
                      testbed: make-me-a-var
                    Hostname: ${cluster-name}-${host-name}
                    Latitude: ${latitude}
                    Longitude: ${longitude}
                    MauriceEndpoint: ${maurice-endpoint}
                    MauricePrivateEndpoint: ${maurice-private-endpoint}
                    Proxy: 
                      http_proxy: ${http-proxy}
                      https_proxy: ${http-proxy}
                    EnableIpv6: true
                    Token: ${site-registration-token}
              - path: /etc/vpm/certified-hardware.yaml
                permissions: 0644
                owner: root
                content: |
                  active: ${certifiedhardware}
                  certifiedHardware:
                    kvm-voltstack-combo:
                      Vpm:
                        PrivateNIC: eth0
                      outsideNic:
                      - eth0
                    kvm-regular-nic-voltmesh:
                      Vpm:
                        PrivateNIC: eth0
                      outsideNic:
                      - eth0
                  primaryOutsideNic: eth0
              runcmd:
                - [ sh, -c, test -e /usr/bin/fsextend  && /usr/bin/fsextend || true ]
              hostname: ${cluster-name}-${host-name}
